name: GitHub Action Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd docs/.vitepress/dist
          echo 'www.hefang.site' > CNAME

          git init
          git config user.email "he529564582@163.com"
          git config user.name "何方"
          git remote add origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/hefangs/coding.git"
          git fetch origin gh-pages
          git checkout -b deploy-branch
          git merge origin/gh-pages
          git add -A
          CURRENT_DATE=$(TZ='Asia/Shanghai' date +"%Y-%m-%d_%H:%M:%S")
          COMMIT_MESSAGE="deploy.yml-$CURRENT_DATE"
          git commit -m "$COMMIT_MESSAGE" || echo "No changes to commit"
          git push -f origin deploy-branch:gh-pages
