name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create a temporary directory to hold the new build
        mkdir temp
        
        # Clone the existing gh-pages branch into temp directory
        git clone --branch gh-pages "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/hefangs/coding.git" temp
        
        # Copy the newly built files to temp directory
        rsync -av --delete --exclude=".git" docs/.vitepress/dist/ temp/
        
        # Navigate to the temp directory
        cd temp
        echo 'www.hefang.site' > CNAME
        # Configure git user
        git config user.name "何方"
        git config user.email "he529564582@163.com"
        
        # Commit and push changes
        git add -A
        CURRENT_DATE=$(TZ='Asia/Shanghai' date +"%Y-%m-%d_%H:%M:%S")
        COMMIT_MESSAGE="deploy.yml-$CURRENT_DATE"
        git commit -m "$COMMIT_MESSAGE"
        git commit -m "deploy-$COMMIT_MESSAGE"
        git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/hefangs/coding.git" gh-pages
