
name: Sync to Aliyun

on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.6.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm 

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build with VitePress
        run: pnpm run build 

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist
          name: github-pages


      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./downloaded-artifact

      - name: Verify artifact download
        run: ls -l ./downloaded-artifact/ 

      - name: Deploy to Aliyun
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 106.15.79.229
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          source: "./downloaded-artifact/artifact.tar"
          target: "/app/site/artifact.tar"

      - name: Unpack and clean up on Aliyun
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 106.15.79.229
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          script: |
            cd /app/site
            rm -rf *
            tar -xvf artifact.tar
            rm artifact.tar
