name: Deploy to Aliyun

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.6.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build and package
        run: |
          pnpm run build
          tar -czf dist.tar.gz -C docs/.vitepress/dist .
    
      - name: Clean Remote Directory
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: 106.15.79.229
            username: ${{ secrets.ALIYUN_USERNAME }}
            password: ${{ secrets.ALIYUN_PASSWORD }}
            script: |
                rm -rf /app/site/html* || true

      - name: Deploy to Aliyun
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 106.15.79.229
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          source: "dist.tar.gz"
          target: "/app/site/html"

      - name: Unpack and clean up
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 106.15.79.229
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          script: |
            tar -xzf /app/site/html/dist.tar.gz -C /app/site/html
            rm /app/site/html/dist.tar.gz
