
name: Sync to Aliyun

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# concurrency:
#   group: pages
#   cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.6.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm 

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build with VitePress
        run: pnpm run build 

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist
          name: github-pages
      # 确认打包文件路径和内容
      - name: Confirm artifact upload
        run: ls -al /home/runner/work/_temp
      # 上传打包文件后，检查路径
      - name: Confirm artifact upload
        run: |
          echo "Checking /home/runner/work/_temp for github-pages.zip"
          find /home/runner/work/_temp -name "github-pages.zip"

      # 如果在 _temp 目录没有找到文件，也可以检查整个文件系统
      - name: Find github-pages.zip in the entire filesystem
        run: find / -name "github-pages.zip" 2>/dev/null


      # - name: Download artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: github-pages
      #     path: /tmp/github-pages

      # - name: Deploy to Aliyun
      #   uses: appleboy/scp-action@v0.1.7
      #   with:
      #     host: 106.15.79.229
      #     username: ${{ secrets.ALIYUN_USERNAME }}
      #     password: ${{ secrets.ALIYUN_PASSWORD }}
      #     source: "/tmp/github-pages/github-pages.zip"
      #     target: "/app/site/github-pages.zip"

      # - name: Unpack and clean up on Aliyun
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: 106.15.79.229
      #     username: ${{ secrets.ALIYUN_USERNAME }}
      #     password: ${{ secrets.ALIYUN_PASSWORD }}
      #     script: |
      #       cd /app/site
      #       rm -rf *
      #       unzip github-pages.zip
      #       rm github-pages.zip
