name: Sync to Aliyun

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.6.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build with VitePress
        run: pnpm run build

      - name: Create zip file
        run: |
          cd docs/.vitepress/dist
          zip -r /tmp/github-pages/github-pages.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: /tmp/github-pages/github-pages.zip
          retention-days: 1

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: github-pages
          path: /tmp/github-pages

      - name: Verify artifact file
        run: |
          echo "Checking files in /tmp/github-pages"
          ls -al /tmp/github-pages

      - name: Deploy to Aliyun
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 106.15.79.229
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          source: "/tmp/github-pages/github-pages.zip"
          target: "/app/site/github-pages.zip"

      - name: Unpack and clean up on Aliyun
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 106.15.79.229
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          script: |
            cd /app/site
            rm -rf *
            unzip github-pages.zip
            rm github-pages.zip
